<a href="https://colab.research.google.com/github/SujalGodse/Pratical_Machine_Learning-PML-/blob/main/PML_Day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
import sklearn
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression


import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)
from numpy import random
from collections import Counter
from numpy.linalg import inv
from numpy.linalg import eig
import matplotlib
from matplotlib import pyplot as plt
import seaborn as sns
import pylab
from pylab import legend
from pylab import plot, show, title, xlabel, ylabel
import scipy
from scipy import stats
from scipy.stats import binom,poisson,norm,t,expon,f
from sklearn.model_selection import train_test_split

import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp

import statsmodels.stats
from statsmodels.stats.proportion import proportions_ztest

from scipy.stats import chisquare

from scipy.stats import chi2_contingency

from statsmodels.stats import rates
from statsmodels.stats.rates import test_poisson

from statsmodels.stats.rates import test_poisson_2indep

from scipy.stats import chi2

# **Lasso and Ridge Regression**

In [3]:
df = pd.read_excel('/content/drive/MyDrive/CDAC/StudentData.xlsx')
df.head()

,Unnamed: 0,StudyHours,PracticeTests,RevisionHours,CoachingHours,Attendance,MobileUsage,NetflixHours,GamingHours,SocialMedia,SportsHours,Marks
0,0,7.0,2.9,7.1,2.6,77.0,6.9,5.5,2.2,7.9,2.4,184.7
1,1,5.7,4.4,5.9,4.2,82.0,8.8,2.2,4.6,5.0,1.6,185.5
2,2,7.3,4.5,7.6,4.7,85.0,2.2,5.7,1.9,6.2,2.0,189.9
3,3,9.0,3.8,9.4,4.0,85.2,6.1,6.7,0.9,5.1,3.3,190.5
4,4,5.5,4.8,5.1,4.8,82.7,3.7,4.8,0.7,5.1,2.2,185.0

In [4]:
df = df.drop('Unnamed: 0', axis=1)
df.head()

,StudyHours,PracticeTests,RevisionHours,CoachingHours,Attendance,MobileUsage,NetflixHours,GamingHours,SocialMedia,SportsHours,Marks
0,7.0,2.9,7.1,2.6,77.0,6.9,5.5,2.2,7.9,2.4,184.7
1,5.7,4.4,5.9,4.2,82.0,8.8,2.2,4.6,5.0,1.6,185.5
2,7.3,4.5,7.6,4.7,85.0,2.2,5.7,1.9,6.2,2.0,189.9
3,9.0,3.8,9.4,4.0,85.2,6.1,6.7,0.9,5.1,3.3,190.5
4,5.5,4.8,5.1,4.8,82.7,3.7,4.8,0.7,5.1,2.2,185.0

In [5]:
# Split for train-test
x_train, x_test, y_train, y_test = train_test_split(df.drop('Marks', axis=1),df.Marks, test_size=0.2, random_state=20)

In [6]:
# Add constant term
x_train = sm.add_constant(x_train, prepend=False)
x_test = sm.add_constant(x_test, prepend=False)

In [7]:
# Prepare the model
mod1 = sm.OLS(y_train,x_train).fit()

print(mod1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Marks   R-squared:                       0.722
Model:                            OLS   Adj. R-squared:                  0.682
Method:                 Least Squares   F-statistic:                     17.96
Date:                Fri, 05 Jun 2026   Prob (F-statistic):           1.38e-15
Time:                        06:18:37   Log-Likelihood:                -266.22
No. Observations:                  80   AIC:                             554.4
Df Residuals:                      69   BIC:                             580.6
Df Model:                          10
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
StudyHours        4.9723      2.752      1.807      0.075      -0.518      10.462
PracticeTests     6.1438      3.575      1.719      0.090      -0.987      13.275
RevisionHours    -0.7379      2.690     -0.274      0.785      -6.105       4.629
CoachingHours    -2.0754      3.521     -0.589      0.558      -9.100       4.949
Attendance        1.1862      0.170      6.996      0.000       0.848       1.524
MobileUsage       0.5540      0.473      1.170      0.246      -0.390       1.498
NetflixHours      0.1115      0.402      0.277      0.783      -0.691       0.914
GamingHours       0.1750      0.567      0.309      0.759      -0.956       1.306
SocialMedia       0.1079      0.494      0.219      0.828      -0.877       1.093
SportsHours      -1.2888      0.902     -1.428      0.158      -3.089       0.511
const            37.8871     15.547      2.437      0.017       6.873      68.902
==============================================================================
Omnibus:                        5.697   Durbin-Watson:                   2.195
Prob(Omnibus):                  0.058   Jarque-Bera (JB):                5.022
Skew:                          -0.493   Prob(JB):                       0.0812
Kurtosis:                       3.730   Cond. No.                     1.65e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.65e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

## **Multicollinearity**

It occurs when there are certain pair of input factors which have a very high value corelation coefficient because of this they will change the effect of other variables in the models.

In order to detect Multicollinearity we can calculate VIF(Variance Inflation Factor) value for each column.

Ideally VIF should be less then 10.

In [8]:
# corelation coefficient between all the pairs
df.corr()

,StudyHours,PracticeTests,RevisionHours,CoachingHours,Attendance,MobileUsage,NetflixHours,GamingHours,SocialMedia,SportsHours,Marks
StudyHours,1.000000,-0.137275,0.985756,-0.166741,-0.139500,-0.148479,0.039702,-0.119595,-0.116330,0.054158,0.461595
PracticeTests,-0.137275,1.000000,-0.136466,0.982391,0.187605,-0.129208,0.083350,0.098441,0.137525,0.060396,0.455356
RevisionHours,0.985756,-0.136466,1.000000,-0.164784,-0.149062,-0.170147,0.023863,-0.119828,-0.152964,0.079607,0.448704
CoachingHours,-0.166741,0.982391,-0.164784,1.000000,0.230122,-0.115819,0.088085,0.076729,0.100994,0.056112,0.444800
Attendance,-0.139500,0.187605,-0.149062,0.230122,1.000000,-0.090584,0.113714,-0.018171,0.115444,-0.152492,0.430057
MobileUsage,-0.148479,-0.129208,-0.170147,-0.115819,-0.090584,1.000000,-0.086980,0.093279,-0.107880,-0.072796,-0.104220
NetflixHours,0.039702,0.083350,0.023863,0.088085,0.113714,-0.086980,1.000000,-0.106991,0.125457,0.082534,0.140267
GamingHours,-0.119595,0.098441,-0.119828,0.076729,-0.018171,0.093279,-0.106991,1.000000,-0.065969,0.217792,-0.040819
SocialMedia,-0.116330,0.137525,-0.152964,0.100994,0.115444,-0.107880,0.125457,-0.065969,1.000000,-0.212731,0.066168
SportsHours,0.054158,0.060396,0.079607,0.056112,-0.152492,-0.072796,0.082534,0.217792,-0.212731,1.000000,-0.086149
Marks,0.461595,0.455356,0.448704,0.444800,0.430057,-0.104220,0.140267,-0.040819,0.066168,-0.086149,1.000000

In [9]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

x = df.drop('Marks', axis=1)

vif_df = pd.DataFrame()
vif_df['Variable'] = x.columns
vif_df['VIF'] = [
    variance_inflation_factor(x.values, i)
    for i in range(x.shape[1])
]

print("\nVIF VALUES")
print(vif_df.sort_values('VIF', ascending=False))

VIF VALUES
        Variable         VIF
3  CoachingHours  448.533988
1  PracticeTests  444.040942
0     StudyHours  436.685659
2  RevisionHours  407.771297
4     Attendance   60.859442
8    SocialMedia   15.561370
5    MobileUsage    7.811828
9    SportsHours    5.976866
7    GamingHours    5.890728
6   NetflixHours    4.989462

from above output we noticed that the same factor which have a heavy or high corelation coefficient between them are also having VIF value.

In [11]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

x = df.drop(['Marks','CoachingHours','StudyHours'], axis=1)

vif_df = pd.DataFrame()
vif_df['Variable'] = x.columns
vif_df['VIF'] = [
    variance_inflation_factor(x.values, i)
    for i in range(x.shape[1])
]

print("\nVIF VALUES")
print(vif_df.sort_values('VIF', ascending=False))

VIF VALUES
        Variable        VIF
2     Attendance  54.670801
0  PracticeTests  14.844545
6    SocialMedia  13.981452
1  RevisionHours  10.080112
3    MobileUsage   7.657400
7    SportsHours   5.898704
5    GamingHours   5.745141
4   NetflixHours   4.937682

## **Standardization**

Unless and until standardization is performed L1 and L2 cannot be performed

In [13]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.preprocessing import StandardScaler

x = df.drop('Marks', axis=1)
y=df.Marks
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)
x_scaled = pd.DataFrame(x_scaled, columns=x.columns)
x_scaled.head()

,StudyHours,PracticeTests,RevisionHours,CoachingHours,Attendance,MobileUsage,NetflixHours,GamingHours,SocialMedia,SportsHours
0,0.670394,-1.496553,0.683348,-1.717666,-1.459355,1.155915,0.683910,-0.542372,0.772477,0.389973
1,-0.051056,-0.442642,0.049150,-0.602751,-0.514177,2.188467,-0.870431,1.109522,-0.782126,-0.439756
2,0.836882,-0.372382,0.947597,-0.254340,0.052930,-1.398293,0.778112,-0.748858,-0.138842,-0.024892
3,1.780318,-0.864207,1.898893,-0.742115,0.090737,0.721156,1.249125,-1.437147,-0.728519,1.323418
4,-0.162049,-0.161600,-0.373648,-0.184658,-0.381852,-0.583120,0.354201,-1.574805,-0.728519,0.182540

## **Linear Model**

In [22]:
# To get the optimum value of alpha for Lasso regression

from sklearn.linear_model import LassoCV
lassocv=LassoCV(cv=5)
lassocv.fit(x_scaled,y)
print(lassocv.alpha_)

from sklearn.linear_model import LinearRegression
regr1 = LinearRegression()
regr1.fit(x_scaled,y)
print(regr1.coef_)

regr1.intercept_
print(regr1.feature_names_in_)

0.46968573975480105
[ 5.50805023  7.25112668  2.0336992  -1.39211411  5.28411473  1.09301416
  0.58200739  0.0777879   0.1418704  -1.05017386]
['StudyHours' 'PracticeTests' 'RevisionHours' 'CoachingHours' 'Attendance'
 'MobileUsage' 'NetflixHours' 'GamingHours' 'SocialMedia' 'SportsHours']

## **Ridge Regression**

In [27]:
from sklearn.linear_model import RidgeCV
ridgecv=RidgeCV(cv=5)
ridgecv.fit(x_scaled,y)
print(ridgecv.alpha_)

ridge = Ridge(alpha=10)
ridge.fit(x_scaled,y)
print(ridge.coef_)
ridge.intercept_
print(regr1.feature_names_in_)

10.0
[ 3.82980281  3.32971683  3.3198266   2.26051693  4.63360394  0.85365738
  0.59599171  0.14077832  0.33850811 -1.0176817 ]
['StudyHours' 'PracticeTests' 'RevisionHours' 'CoachingHours' 'Attendance'
 'MobileUsage' 'NetflixHours' 'GamingHours' 'SocialMedia' 'SportsHours']

## **Lasso Regression**

In [28]:
from sklearn.linear_model import LassoCV
lassocv=LassoCV(cv=5)
lassocv.fit(x_scaled,y)
print(lassocv.alpha_)

lasso = Lasso(alpha=1)
lasso.fit(x_scaled,y)
print(lasso.coef_)
print(lasso.intercept_)

0.46968573975480105
[ 6.04772327  4.72885822  0.          0.          4.34663537  0.
  0.         -0.          0.         -0.03101151]
185.09500000000003

# **Logistic Regression**

- Binary - 2 Possible responses
- Nominal - >2 Possible levels
- Ordinal - levels have a logical order

## **Binary Liogistic Regresssion**

In [29]:
df = pd.read_excel('/content/drive/MyDrive/CDAC/CDAC_DataBook.xlsx',sheet_name='diabetes')
df.head()

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,DietType
0,148,72,35,0,33.6,0.63,50,1,1
1,85,66,29,0,26.6,0.35,31,0,2
2,183,64,0,0,23.3,0.67,32,1,1
3,89,66,23,94,28.1,0.17,21,0,1
4,137,40,35,168,43.1,2.29,33,1,1

In [30]:
df =df[['Glucose','BloodPressure','Age','DietType','Outcome']]

x = df.drop('Outcome', axis=1)
y = df.Outcome

In [31]:
diet_dummy = pd.get_dummies(x.DietType, drop_first=True, prefix='Diet').astype(int)
x = x.drop('DietType', axis=1)
x = pd.concat([x, diet_dummy], axis=1)

In [32]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=20)

x_train = sm.add_constant(x_train, prepend=False)
x_test = sm.add_constant(x_test, prepend=False)

mod3 = sm.Logit(y_train, x_train).fit()
print(mod3.summary())

Optimization terminated successfully.
         Current function value: 0.333614
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                Outcome   No. Observations:                  614
Model:                          Logit   Df Residuals:                      608
Method:                           MLE   Df Model:                            5
Date:                Fri, 05 Jun 2026   Pseudo R-squ.:                  0.4848
Time:                        11:26:47   Log-Likelihood:                -204.84
converged:                       True   LL-Null:                       -397.59
Covariance Type:            nonrobust   LLR p-value:                 3.933e-81
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
Glucose           0.0368      0.005      7.867      0.000       0.028       0.046
BloodPressure     0.0058      0.007      0.850      0.395      -0.008       0.019
Age               0.0317      0.011      2.908      0.004       0.010       0.053
Diet_2           -3.9276      0.323    -12.142      0.000      -4.562      -3.294
Diet_3           -2.7806      0.344     -8.076      0.000      -3.455      -2.106
const            -4.3877      0.730     -6.012      0.000      -5.818      -2.957
=================================================================================

From above output we can see we have 3 continuous coefficient(Glucose,BP,Age) and 2 categoical coeffficient (Diet_2,Diet_2)

ex. Glucose : H0 -> Glucose does not influence Diabetes / Glucose = 0

If coeficient + then outcome increase with cooeficient increase


if coeficient - then seasow

In [37]:
x_test.iloc[0]

Glucose          108.0
BloodPressure     66.0
Age               42.0
Diet_2             1.0
Diet_3             0.0
const              1.0
Name: 143, dtype: float64

In [38]:
z = (0.0368*108) + (0.0058*66) + (0.0317*42) + (-3.9276*1) + (-4.3877)

In [39]:
1/(1+np.exp(-z))

np.float64(0.0674396967938822)